//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5472 版自动生成。
// 
namespace smpBayerRegCode.refServiceHcwl {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceRDSoap", Namespace="http://211.97.0.4/")]
    public partial class ServiceRD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ServiceRD() {
            this.Url = "http://173.5.28.153/gspupload/servicerd.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://211.97.0.4/wsCmd", RequestNamespace="http://211.97.0.4/", ResponseNamespace="http://211.97.0.4/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int wsCmd(string AQuery, string AConnectString) {
            object[] results = this.Invoke("wsCmd", new object[] {
                        AQuery,
                        AConnectString});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwsCmd(string AQuery, string AConnectString, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wsCmd", new object[] {
                        AQuery,
                        AConnectString}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndwsCmd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://211.97.0.4/gspupload", RequestNamespace="http://211.97.0.4/", ResponseNamespace="http://211.97.0.4/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int gspupload(string AConnectString, string carton_nbr, string carton_sqe_nbr, string orig_nbr, string orig_type, string nbr_type, string batch_nbr, string[] gsp_array) {
            object[] results = this.Invoke("gspupload", new object[] {
                        AConnectString,
                        carton_nbr,
                        carton_sqe_nbr,
                        orig_nbr,
                        orig_type,
                        nbr_type,
                        batch_nbr,
                        gsp_array});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingspupload(string AConnectString, string carton_nbr, string carton_sqe_nbr, string orig_nbr, string orig_type, string nbr_type, string batch_nbr, string[] gsp_array, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("gspupload", new object[] {
                        AConnectString,
                        carton_nbr,
                        carton_sqe_nbr,
                        orig_nbr,
                        orig_type,
                        nbr_type,
                        batch_nbr,
                        gsp_array}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endgspupload(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://211.97.0.4/gspupload_test", RequestNamespace="http://211.97.0.4/", ResponseNamespace="http://211.97.0.4/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int gspupload_test(string AConnectString, string carton_nbr, string carton_sqe_nbr, string orig_nbr, string orig_type, string nbr_type, string batch_nbr, string user_id, string[] gsp_array) {
            object[] results = this.Invoke("gspupload_test", new object[] {
                        AConnectString,
                        carton_nbr,
                        carton_sqe_nbr,
                        orig_nbr,
                        orig_type,
                        nbr_type,
                        batch_nbr,
                        user_id,
                        gsp_array});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingspupload_test(string AConnectString, string carton_nbr, string carton_sqe_nbr, string orig_nbr, string orig_type, string nbr_type, string batch_nbr, string user_id, string[] gsp_array, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("gspupload_test", new object[] {
                        AConnectString,
                        carton_nbr,
                        carton_sqe_nbr,
                        orig_nbr,
                        orig_type,
                        nbr_type,
                        batch_nbr,
                        user_id,
                        gsp_array}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endgspupload_test(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://211.97.0.4/wsCmdScalar", RequestNamespace="http://211.97.0.4/", ResponseNamespace="http://211.97.0.4/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsCmdScalar(string AQuery, string AConnectString) {
            object[] results = this.Invoke("wsCmdScalar", new object[] {
                        AQuery,
                        AConnectString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwsCmdScalar(string AQuery, string AConnectString, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wsCmdScalar", new object[] {
                        AQuery,
                        AConnectString}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwsCmdScalar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://211.97.0.4/wsGetTable", RequestNamespace="http://211.97.0.4/", ResponseNamespace="http://211.97.0.4/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable wsGetTable(string AQuery, string AConnectString) {
            object[] results = this.Invoke("wsGetTable", new object[] {
                        AQuery,
                        AConnectString});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwsGetTable(string AQuery, string AConnectString, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wsGetTable", new object[] {
                        AQuery,
                        AConnectString}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndwsGetTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
}
